services:
  # Services DA
  App\Service\da\FileUploaderForDAService:
    public: true

  App\Service\da\DaFilterService:
    public: true

  App\Service\da\DaService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daFileUploader: '@App\Service\da\FileUploaderForDAService'
    public: true

  App\Service\da\DaAfficherService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daService: '@App\Service\da\DaService'
      $userDataService: "@userData.service"
    public: true

  App\Service\da\DaFournisseurService:
    arguments:
      $daModel: '@App\Model\da\DaModel'
      $userDataService: "@userData.service"
    public: true

  App\Service\da\DaCreationService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $userDataService: "@userData.service"
    public: true

  App\Service\da\DaEditionService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daService: '@App\Service\da\DaService'
      $daFileUploader: '@App\Service\da\FileUploaderForDAService'
    public: true

  App\Service\da\DaDetailService:
    arguments:
      $urlGenerator: '@router'
    public: true

  App\Service\da\DwDataService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DaTimelineService:
    arguments:
      $daAfficherModel: '@App\Model\da\DaAfficherModel'
    public: true

  App\Service\da\DocRattacheService:
    arguments:
      $daService: '@App\Service\da\DaService'
      $dwDataService: '@App\Service\da\DwDataService'
    public: true

  # Factories DA
  App\Factory\da\CdeFrnDto\DaSoumissionFacBlFactory:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daSoumissionFacBlModel: '@App\Model\da\DaSoumissionFacBlModel'
      $numeroGenerateurService: '@App\Service\da\NumeroGenerateurService'
      $calculService: '@App\Service\da\DaSoumissionCalculService'
      $dataService: '@App\Service\da\DaSoumissionDataService'
      $securityService: '@App\Service\security\SecurityService'
      $ddpModel: '@App\Model\ddp\DemandePaiementModel'
    public: true

  # Contrôleurs DA
  App\Controller\da\ListeDa\listeDaController:
    autowire: true
    autoconfigure: true
    arguments:
      - "@doctrine.orm.default_entity_manager"
    public: true

  App\Controller\da\Detail\DaDetailReapproController:
    arguments:
      $daService: '@App\Service\da\DaService'
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Controller\da\Validation\DaValidationReapproMensuelController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daService: '@App\Service\da\DaService'
    public: true

  App\Controller\da\Detail\DaDetailAvecDitController:
    arguments:
      $daDetailService: '@App\Service\da\DaDetailService'
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Detail\DaDetailDirectController:
    arguments:
      $daDetailService: '@App\Service\da\DaDetailService'
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Proposition\DaPropositionRefAvecDitController:
    arguments:
      $daFournisseurService: '@App\Service\da\DaFournisseurService'
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Proposition\DaPropositionArticleDirectController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\DossierDa\DaDossierDaController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
    public: true

  App\Controller\da\Affectation\DaAffectationAchatController:
    arguments:
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Creation\DaNewAchatController:
    arguments:
      $daCreationService: '@App\Service\da\DaCreationService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Creation\DaNewReApproMensuelController:
    arguments:
      $daCreationService: '@App\Service\da\DaCreationService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Creation\DaNewAvecDitController:
    arguments:
      $daCreationService: '@App\Service\da\DaCreationService'
      $daModel: '@App\Model\da\DaModel'
      $daFournisseurService: '@App\Service\da\DaFournisseurService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Modification\DaEditDirectController:
    arguments:
      $daEditionService: '@App\Service\da\DaEditionService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Modification\DaEditAvecDitController:
    arguments:
      $daEditionService: '@App\Service\da\DaEditionService'
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Validation\DaValidationAvecDitController:
    arguments:
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Controller\da\Validation\DaValidationDirectController:
    arguments:
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  # Api DA
  App\Api\da\DaAfficherApi:
    arguments:
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true

  App\Api\da\DemandeDevisApi:
    arguments:
      $daService: '@App\Service\da\DaService'
      $daAfficherService: '@App\Service\da\DaAfficherService'
    public: true
