services:
  # Services DA
  App\Service\da\FileUploaderForDAService:
    public: true

  App\Service\da\DaService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daFileUploader: '@App\Service\da\FileUploaderForDAService'
    public: true

  App\Service\da\DaAfficherService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DwDataService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DaTimelineService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\da\DocRattacheService:
    arguments:
      $daService: '@App\Service\da\DaService'
      $dwDataService: '@App\Service\da\DwDataService'
    public: true

  # Factories DA
  App\Factory\da\CdeFrnDto\DaSoumissionFacBlFactory:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $daSoumissionFacBlModel: '@App\Model\da\DaSoumissionFacBlModel'
      $numeroGenerateurService: '@App\Service\da\NumeroGenerateurService'
      $calculService: '@App\Service\da\DaSoumissionCalculService'
      $dataService: '@App\Service\da\DaSoumissionDataService'
      $securityService: '@App\Service\security\SecurityService'
    public: true

  # Contrôleurs DA
  App\Controller\da\ListeDa\listeDaController:
    autowire: true
    autoconfigure: true
    arguments:
      - "@doctrine.orm.default_entity_manager"
    public: true

  App\Controller\da\Detail\DaDetailReapproController:
    arguments:
      $daService: '@App\Service\da\DaService'
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Controller\da\Validation\DaValidationReapproMensuelController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
    public: true

  App\Controller\da\Detail\DaDetailAvecDitController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Controller\da\Detail\DaDetailDirectController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
      $daTimelineService: '@App\Service\da\DaTimelineService'
    public: true

  App\Controller\da\Proposition\DaPropositionRefAvecDitController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
    public: true

  App\Controller\da\Proposition\DaPropositionArticleDirectController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
    public: true

  App\Controller\da\DossierDa\DaDossierDaController:
    arguments:
      $docRattacheService: '@App\Service\da\DocRattacheService'
    public: true
