services:
  App\Mapper\Magasin\CdeFrn\CdeFrnSoumissionMapper:
    public: true

  App\Service\magasin\cdeFrn\CdeFrnSoumissionStore:
    arguments:
      $cache: "@cache.cde_frn_soumission"
    public: true

  App\Factory\magasin\cdeFrn\soumission\CdeFrnSoumisAValidationFactory:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
    public: true

  App\Service\magasin\cdeFrn\CdeFrnSoumissionService:
    arguments:
      $em: "@doctrine.orm.default_entity_manager"
      $store: '@App\Service\magasin\cdeFrn\CdeFrnSoumissionStore'
      $mapper: '@App\Mapper\Magasin\CdeFrn\CdeFrnSoumissionMapper'
      $factory: '@App\Factory\magasin\cdeFrn\soumission\CdeFrnSoumisAValidationFactory'
    public: true

  App\Api\magasin\cdeFrn\GenerateCommandeFournisseurApi:
    arguments:
      $cdeFrnSoumissionService: '@App\Service\magasin\cdeFrn\CdeFrnSoumissionService'

  App\Controller\magasin\commande\soumission\SoumissionCommandeController:
    arguments:
      $cdeFrnSoumissionService: '@App\Service\magasin\cdeFrn\CdeFrnSoumissionService'
