services:
    # Service Twig Environment
    twig:
        class: Twig\Environment
        arguments:
            - '@twig.loader'
            - { debug: true }
        public: true

    twig.loader:
        class: Twig\Loader\FilesystemLoader
        arguments:
            - '%kernel.project_dir%/Views/templates'
            - '%kernel.project_dir%/vendor/symfony/twig-bridge/Resources/views/Form'
        public: true

    # Alias pour Twig\Environment pour l'autowiring
    Twig\Environment: '@twig'

    # Services Twig Extensions
    App\Twig\AppExtension:
        arguments:
            - '@session'
            - '@request_stack'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags: ['twig.extension']

    App\Twig\BreadcrumbExtension:
        arguments:
            - '@App\Service\navigation\BreadcrumbMenuService'
        tags: ['twig.extension']
        public: true

    App\Twig\CarbonExtension:
        tags: ['twig.extension']

    App\Twig\DeleteWordExtension:
        tags: ['twig.extension']

