services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Services de base
    App\Service\:
        resource: '../../src/Service/*'
        exclude:
            - '../../src/Service/dit/or/'
        tags: ['app.service']
        public: true

    App\Model\:
        resource: '../../src/Model/*'
        exclude:
            - '../../src/Model/Model.php'
            - '../../src/Model/dom/DomModel.php'
            - '../../src/Model/Connexion.php'
            - '../../src/Model/DatabaseInformix.php'
            - '../../src/Model/ConnexionDote4.php'
            - '../../src/Model/ConnexionDote4Gcot.php'
            - '../../src/Model/LdapModel.php'
            - '../../src/Model/FileReaderModel.php'
            - '../../src/Model/migration/MigrationDevisModel.php'
        tags: ['app.model']
        public: true

    App\Repository\:
        resource: '../../src/Repository/*'
        tags: ['app.repository']
        public: true
