CREATE TABLE Hff_pages (
	id INT IDENTITY (1, 1),
    nom VARCHAR(255) NOT NULL,
    nom_route varchar(255) NOT NULL,
    lien VARCHAR(255) NOT NULL
    CONSTRAINT PK_hff_pages PRIMARY KEY (id)
);

INSERT INTO Hff_pages (nom, nom_route, lien)
VALUES 
    ('Accueil', 'profil_acceuil', '/Acceuil'),
    ('Authentification (identifiants incorrects)', 'security_signin', '/'),
    ('Nouvelle DIT', 'dit_new', '/dit/new'),
    ('Liste DIT', 'dit_index', '/dit'),
    ('Recherche sur la liste DIT', 'dit_index_search', '/dit'),
    ('Duplication d''une DIT', 'dit_duplication', '/ditDuplication/{id<\d+>}/{numDit<\w+>}'),
    ('Consultation intervention atelier avec DIT', 'dw_interv_ate_avec_dit', '/dw-intervention-atelier-avec-dit/{numDit}'),
    ('Consultation dossier DIT', 'dit_dossier_intervention_atelier', '/dit-dossier-intervention-atelier'),
    ('Nouvelle ordre de mission premier formulaire', 'dom_first_form', '/dom-first-form'),
    ('Nouvelle ordre de mission deuxième formulaire', 'dom_second_form', '/dom-second-form'),
    ('Liste DOM (tous)', 'doms_liste', '/dom-liste'),
    ('Recherche sur la liste DOM (tous)', 'doms_liste_search', '/dom-liste'),
    ('Liste DOM (annulées)', 'dom_list_annuler', '/dom-list-annuler'),
    ('Fiche détail d''un DOM', 'Dom_detail', '/detailDom/{id}'),
    ('Nouvelle BADM premier formulaire', 'badms_newForm1', '/badm-form1'),
    ('Nouvelle BADM deuxième formulaire', 'badms_newForm2', '/badm-form2'),
    ('Liste BADM (tous)', 'badmListe_AffichageListeBadm', '/listBadm'),
    ('Recherche sur la liste BADM (tous)', 'badmListe_AffichageListeBadm_search', '/listBadm'),
    ('Fiche détail d''un BADM', 'BadmDetail_detailBadm', '/detailBadm/{id}'), 
    ('Duplication d''un BADM', 'BadmDupli_dupliBadm', '/dupliBADM/{numBadm}/{id}'), 
    ('Liste BADM (annulées)', 'badm_list_annuler', '/badm-list-annuler'),
    ('Recherche sur la liste BADM (annulées)', 'badm_list_annuler_search', '/badm-list-annuler'),
    ('Nouveau casier premier formulaire', 'casier_nouveau', '/nouveauCasier'),
    ('Nouveau casier deuxième formulaire', 'casiser_formulaireCasier', '/createCasier'),
    ('Liste casier (temporaire)', 'listeTemporaire_affichageListeCasier', '/listTemporaireCasier'),
    ('Recherche sur la liste casier (temporaire)', 'listeTemporaire_affichageListeCasier_search', '/listTemporaireCasier'),
    ('Liste casier (définitive)', 'liste_affichageListeCasier', '/listCasier'),
    ('Recherche sur la liste casier (définitive)', 'liste_affichageListeCasier_search', '/listCasier'),
    ('Liste OR à traiter', 'magasinListe_index', '/liste-magasin'),
    ('Recherche sur la liste OR à traiter', 'magasinListe_index_search', '/liste-magasin'),
    ('Liste OR à livrer', 'magasinListe_or_Livrer', '/liste-or-livrer'),
    ('Recherche sur la liste OR à livrer', 'magasinListe_or_Livrer_search', '/liste-or-livrer'),
    ('Liste CIS à traiter', 'cis_liste_a_traiter', '/cis-liste-a-traiter'),
    ('Recherche sur la liste CIS à traiter', 'cis_liste_a_traiter_search', '/cis-liste-a-traiter'),
    ('Liste CIS à livrer', 'cis_liste_a_livrer', '/cis-liste-a-livrer'),
    ('Recherche sur la liste CIS à livrer', 'cis_liste_a_livrer_search', '/cis-liste-a-livrer'),
    ('Nouvelle demande de support informatique (ticket)', 'demande_support_informatique', '/demande-support-informatique'),
    ('Liste Ticket', 'liste_tik_index', '/tik-liste'),
    ('Recherche sur la liste Ticket', 'liste_tik_index_search', '/tik-liste'),
    ('Fiche détail d''un ticket', 'detail_tik', '/tik-detail/{id<\d+>}'),
    ('Fiche de modification d''un ticket', 'tik_modification_edit', '/tik-modification-edit/{id}'),
    ('Calendrier planning', 'tik_calendar_planning', '/tik-calendar-planning'),
    ('Liste Planning', 'planning_vue', '/planning'),
    ('Recherche sur la liste Planning', 'planning_vue_search', '/planning'),
    ('Procédure d''utilisation', 'badm_index', '/doc/badm'),
    ('Soumission de la facture d''un DIT', 'dit_insertion_facture', '/soumission-facture/{numDit}'),
    ('Soumission de l''OR d''un DIT', 'dit_insertion_or', '/soumission-or/{numDit}'),
    ('Soumission de la RI d''un DIT', 'dit_insertion_ri', '/soumission-ri/{numDit}'),
    ('Fiche détail d''un DIT', 'dit_validationDit', '/ditValidation/{id<\d+>}/{numDit<\w+>}'),
    ('Recherche sur la liste DOM (annulées)', 'dom_list_annuler_search', '/dom-list-annuler'),
;