CREATE TABLE Hff_pages (
	id INT IDENTITY (1, 1),
    nom VARCHAR(255) NOT NULL,
    nom_route varchar(255) NOT NULL,
    lien VARCHAR(255) NOT NULL
    CONSTRAINT PK_hff_pages PRIMARY KEY (id)
);

INSERT INTO TABLE Hff_pages (nom, nom_route, lien)
VALUES 
    ('page_accueil', 'profil_acceuil', '/Acceuil'),
    ('page_authentification', 'security_signin', '/'),
    ('page_nouvelle_DIT', 'dit_new', '/dit/new'),
    ('page_consultation_liste_DIT', 'dit_index', '/dit'),
    ('page_duplication_d_un_DIT', 'dit_duplication', '/ditDuplication/{id<\d+>}/{numDit<\w+>}'),
    ('page_consultation_intervention_atelier_avec_DIT', 'dw_interv_ate_avec_dit', '/dw-intervention-atelier-avec-dit/{numDit}'),
    ('page_consultation_dossier_DIT', 'dit_dossier_intervention_atelier', '/dit-dossier-intervention-atelier'),
    ('page_nouvelle_ordre_de_mission_premier_form', 'dom_first_form', '/dom-first-form'),
    ('page_nouvelle_ordre_de_mission_deuxieme_form', 'dom_second_form', '/dom-second-form'),
    ('page_consultation_liste_ordre_de_mission_tous', 'doms_liste', '/dom-liste'),
    ('page_consultation_liste_ordre_de_mission_annulee', 'dom_list_annuler', '/dom-list-annuler'),
    ('page_consultation_detail_DOM', 'Dom_detail', '/detailDom/{id}'),
    ('page_nouvelle_demande_BADM_premier_form', 'badms_newForm1', '/badm-form1'),
    ('page_nouvelle_demande_BADM_deuxieme_form', 'badms_newForm2', '/badm-form2'),
    ('page_consultation_liste_BADM_tous', 'badmListe_AffichageListeBadm', '/listBadm'),
    ('page_consultation_detail_BADM', 'BadmDetail_detailBadm', '/detailBadm/{id}'), 
    ('page_duplication_d_un_BADM', 'BadmDupli_dupliBadm', '/dupliBADM/{numBadm}/{id}'), 
    ('page_consultation_liste_BADM_annulee', 'badm_list_annuler', '/badm-list-annuler'),
    ('page_nouveau_casier_premier_form', 'casier_nouveau', '/nouveauCasier'),
    ('page_nouveau_casier_deuxieme_form', 'casiser_formulaireCasier', '/createCasier'),
    ('page_consultation_liste_temporaire_casier', 'listeTemporaire_affichageListeCasier', '/listTemporaireCasier'),
    ('page_consultation_liste_definitive_casier', 'liste_affichageListeCasier', '/listCasier'),
    ('page_consultation_liste_des_OR_a_traiter', 'magasinListe_index', '/liste-magasin'),
    ('page_consultation_liste_des_OR_a_livrer', 'magasinListe_or_Livrer', '/liste-or-livrer'),
    ('page_consultation_liste_des_CIS_a_traiter', 'cis_liste_a_traiter', '/cis-liste-a-traiter'),
    ('page_consultation_liste_des_CIS_a_livrer', 'cis_liste_a_livrer', '/cis-liste-a-livrer'),
    ('page_nouvelle_demande_support_informatique_TIK', 'demande_support_informatique', '/demande-support-informatique'),
    ('page_consultation_liste_support_informatique_TIK', 'liste_tik_index', '/tik-liste'),
    ('page_consultation_detail_support_informatique_TIK', 'detail_tik', '/tik-detail/{id<\d+>}'),
    ('page_consultation_modification_support_informatique_TIK', 'tik_modification_edit', '/tik-modification-edit/{id}'),
    ('page_consultation_calendrier_planning', 'tik_calendar_planning', '/tik-calendar-planning'),
    ('page_consultation_liste_planning', 'planning_vue', '/planning'),
    ('page_consultation_procedure_utilisation', 'badm_index', '/doc/badm'),
    ('page_admin_consultation_liste_profile_utilisateurs', 'user_list', '/admin/user/list'),
    ('page_admin_nouveau_profile_utilisateur', 'user_index', '/admin/user'),
    ('page_admin_modification_profile_utilisateur', 'user_update', '/admin/user/edit/{id}'),
    ('page_admin_consultation_liste_agence_service_autoriser_utilisateurs', 'autoriser_index', '/admin/autoriser'),
    ('page_admin_nouvelle_agence_service_autoriser_utilisateur', 'autoriser_new', '/admin/autoriser/new'),
    ('page_admin_modification_agence_service_autoriser_utilisateur', 'autoriser_update', '/admin/autoriser/edit/{id}'),
    ('page_admin_consultation_liste_personnels', 'personnel_index', '/admin/personnel'),
    ('page_admin_nouveau_personnel', 'personnnel_new', '/admin/personnel/new'),
    ('page_admin_detail_personnel', 'personnel_show', '/admin/personnel/show/{id}'),
    ('page_admin_modification_personnel', 'personnel_update', '/admin/personnel/edit/{id}'),
    ('page_admin_consultation_liste_agence_service_IRIUM', 'AgServIrium_index', '/admin/agServIrium'),
    ('page_admin_nouveau_agence_service_IRIUM', 'AgServIrium_new', '/admin/agServIrium/new'),
    ('page_admin_modification_agence_service_IRIUM', 'AgServIrium_update', '/admin/agServIrium/edit/{id}'),
    ('page_admin_consultation_liste_roles', 'role_index', '/admin/role'),
    ('page_admin_nouveau_role', 'role_new', '/admin/role/new'),
    ('page_admin_modification_role', 'role_update', '/admin/role/edit/{id}'),
    ('page_admin_consultation_liste_permissions', 'permission_index', '/admin/permission'),
    ('page_admin_nouvelle_permission', 'permission_new', '/admin/permission/new'),
    ('page_admin_modification_permission', 'permission_update', '/admin/permission/edit/{id}'),
    ('page_admin_liste_utilisateurs', 'utilisateur_index', '/admin/utilisateur'),
    ('page_admin_nouveau_utilisateur', 'utilisateur_new', '/admin/utilisateur/new'),
    ('page_admin_detail_utilisateur', 'utilisateur_show', '/admin/utilisateur/show/{id}'),
    ('page_admin_modification_utilisateur', 'utilisateur_update', '/admin/utilisateur/edit/{id}'),
;

INSERT INTO TABLE Hff_pages (nom, nom_route, lien)
VALUES 
    ('page_soumission_facture_d_un_DIT', 'dit_insertion_facture', '/soumission-facture/{numDit}'),
    ('page_soumission_OR_d_un_DIT', 'dit_insertion_or', '/soumission-or/{numDit}'),
    ('page_soumission_RI_d_un_DIT', 'dit_insertion_ri', '/soumission-ri/{numDit}'),
    ('page_consultation_fiche_detail_DIT', 'dit_validationDit', '/ditValidation/{id<\d+>}/{numDit<\w+>}'),
    ('page_soumission_commande', 'dit_insertion_cde', '/soumission-cde'),
;