<?php

namespace App\Proxies\__CG__\App\Entity\admin\ddp;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocDemandePaiement extends \App\Entity\admin\ddp\DocDemandePaiement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'numeroDdp', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'typeDocumentId', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'nomFichier', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'nomDossier', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'numDdr', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'numeroVersion', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'dateModification'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'numeroDdp', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'typeDocumentId', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'nomFichier', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'nomDossier', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'numDdr', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'numeroVersion', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\ddp\\DocDemandePaiement' . "\0" . 'dateModification'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DocDemandePaiement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDdp', []);

        return parent::getNumeroDdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDdp($numeroDdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDdp', [$numeroDdp]);

        return parent::setNumeroDdp($numeroDdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDocumentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDocumentId', []);

        return parent::getTypeDocumentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDocumentId($typeDocumentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDocumentId', [$typeDocumentId]);

        return parent::setTypeDocumentId($typeDocumentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomFichier', []);

        return parent::getNomFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomFichier($nomFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomFichier', [$nomFichier]);

        return parent::setNomFichier($nomFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDossier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDossier', []);

        return parent::getNomDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDossier($nomDossier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDossier', [$nomDossier]);

        return parent::setNomDossier($nomDossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumDdr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumDdr', []);

        return parent::getNumDdr();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumDdr($numDdr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumDdr', [$numDdr]);

        return parent::setNumDdr($numDdr);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroVersion', []);

        return parent::getNumeroVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroVersion($numeroVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroVersion', [$numeroVersion]);

        return parent::setNumeroVersion($numeroVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\admin\ddp\DocDemandePaiement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTimeInterface $dateModification): \App\Entity\admin\ddp\DocDemandePaiement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        parent::onPreUpdate();
    }

}
