<?php

namespace App\Proxies\__CG__\App\Entity\dw;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DwProcessusProcedure extends \App\Entity\dw\DwProcessusProcedure implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'id', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'idDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'nomDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'processusLie', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'typeDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'dateDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'dateProchainRevue', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'nomResponsable', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'emailResponsable', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'dateModification', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'numeroVersion', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'codeService', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'codeAgence', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'perimetre', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'motCle', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'numeroVersion2', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'path'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'id', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'idDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'nomDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'processusLie', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'typeDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'dateDocument', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'dateProchainRevue', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'nomResponsable', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'emailResponsable', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'dateModification', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'numeroVersion', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'codeService', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'codeAgence', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'perimetre', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'motCle', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'numeroVersion2', '' . "\0" . 'App\\Entity\\dw\\DwProcessusProcedure' . "\0" . 'path'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DwProcessusProcedure $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDocument', []);

        return parent::getIdDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDocument($idDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDocument', [$idDocument]);

        return parent::setIdDocument($idDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDocument', []);

        return parent::getNomDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDocument($nomDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDocument', [$nomDocument]);

        return parent::setNomDocument($nomDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessusLie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessusLie', []);

        return parent::getProcessusLie();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessusLie($processusLie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessusLie', [$processusLie]);

        return parent::setProcessusLie($processusLie);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDocument', []);

        return parent::getTypeDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDocument($typeDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDocument', [$typeDocument]);

        return parent::setTypeDocument($typeDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDocument', []);

        return parent::getDateDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDocument($dateDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDocument', [$dateDocument]);

        return parent::setDateDocument($dateDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateProchainRevue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateProchainRevue', []);

        return parent::getDateProchainRevue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateProchainRevue($dateProchainRevue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateProchainRevue', [$dateProchainRevue]);

        return parent::setDateProchainRevue($dateProchainRevue);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomResponsable', []);

        return parent::getNomResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomResponsable($nomResponsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomResponsable', [$nomResponsable]);

        return parent::setNomResponsable($nomResponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailResponsable', []);

        return parent::getEmailResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailResponsable($emailResponsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailResponsable', [$emailResponsable]);

        return parent::setEmailResponsable($emailResponsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification($dateModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroVersion', []);

        return parent::getNumeroVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroVersion($numeroVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroVersion', [$numeroVersion]);

        return parent::setNumeroVersion($numeroVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeService', []);

        return parent::getCodeService();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeService($codeService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeService', [$codeService]);

        return parent::setCodeService($codeService);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeAgence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAgence', []);

        return parent::getCodeAgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAgence($codeAgence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAgence', [$codeAgence]);

        return parent::setCodeAgence($codeAgence);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerimetre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerimetre', []);

        return parent::getPerimetre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerimetre($perimetre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerimetre', [$perimetre]);

        return parent::setPerimetre($perimetre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotCle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotCle', []);

        return parent::getMotCle();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotCle($motCle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotCle', [$motCle]);

        return parent::setMotCle($motCle);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroVersion2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroVersion2', []);

        return parent::getNumeroVersion2();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroVersion2($numeroVersion2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroVersion2', [$numeroVersion2]);

        return parent::setNumeroVersion2($numeroVersion2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

}
