<?php

namespace App\Proxies\__CG__\App\Entity\dw;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DwCommande extends \App\Entity\dw\DwCommande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'idCde', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'numeroCde', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'numeroOR', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'heureCreation', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'dateDerniereModification', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'heureDerniereModification', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'totalPage', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'extensionFichier', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'tailleFichier', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'path', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'tiroir', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'ordresDeReparation'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'idCde', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'numeroCde', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'numeroOR', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'heureCreation', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'dateDerniereModification', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'heureDerniereModification', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'totalPage', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'extensionFichier', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'tailleFichier', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'path', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'tiroir', '' . "\0" . 'App\\Entity\\dw\\DwCommande' . "\0" . 'ordresDeReparation'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DwCommande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCde', []);

        return parent::getIdCde();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCde($idCde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCde', [$idCde]);

        return parent::setIdCde($idCde);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCde', []);

        return parent::getNumeroCde();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCde($numeroCde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCde', [$numeroCde]);

        return parent::setNumeroCde($numeroCde);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroOR()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroOR', []);

        return parent::getNumeroOR();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroOR($numeroOR)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroOR', [$numeroOR]);

        return parent::setNumeroOR($numeroOR);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureCreation', []);

        return parent::getHeureCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureCreation($heureCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureCreation', [$heureCreation]);

        return parent::setHeureCreation($heureCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDerniereModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDerniereModification', []);

        return parent::getDateDerniereModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDerniereModification($dateDerniereModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDerniereModification', [$dateDerniereModification]);

        return parent::setDateDerniereModification($dateDerniereModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDerniereModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDerniereModification', []);

        return parent::getHeureDerniereModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDerniereModification($heureDerniereModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDerniereModification', [$heureDerniereModification]);

        return parent::setHeureDerniereModification($heureDerniereModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPage', []);

        return parent::getTotalPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPage($totalPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPage', [$totalPage]);

        return parent::setTotalPage($totalPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtensionFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtensionFichier', []);

        return parent::getExtensionFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtensionFichier($extensionFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtensionFichier', [$extensionFichier]);

        return parent::setExtensionFichier($extensionFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTailleFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTailleFichier', []);

        return parent::getTailleFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setTailleFichier($tailleFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTailleFichier', [$tailleFichier]);

        return parent::setTailleFichier($tailleFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiroir(): ?\App\Entity\dw\DwTiroir
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiroir', []);

        return parent::getTiroir();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiroir(?\App\Entity\dw\DwTiroir $tiroir): \App\Entity\dw\DwCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiroir', [$tiroir]);

        return parent::setTiroir($tiroir);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdresDeReparation(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdresDeReparation', []);

        return parent::getOrdresDeReparation();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdreDeReparation(\App\Entity\dw\DwOrdreDeReparation $ordreDeReparation): \App\Entity\dw\DwCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdreDeReparation', [$ordreDeReparation]);

        return parent::addOrdreDeReparation($ordreDeReparation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdreDeReparation(\App\Entity\dw\DwOrdreDeReparation $ordreDeReparation): \App\Entity\dw\DwCommande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdreDeReparation', [$ordreDeReparation]);

        return parent::removeOrdreDeReparation($ordreDeReparation);
    }

}
