<?php

namespace App\Proxies\__CG__\App\Entity\admin\historisation\documentOperation;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TypeDocument extends \App\Entity\admin\historisation\documentOperation\TypeDocument implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'typeDocument', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'libelleDocument', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'heureCreation', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'heureModification', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'historiqueOperationDoc'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'typeDocument', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'libelleDocument', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'heureCreation', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'heureModification', '' . "\0" . 'App\\Entity\\admin\\historisation\\documentOperation\\TypeDocument' . "\0" . 'historiqueOperationDoc'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TypeDocument $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDocument', []);

        return parent::getTypeDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDocument(string $typeDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDocument', [$typeDocument]);

        return parent::setTypeDocument($typeDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleDocument', []);

        return parent::getLibelleDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleDocument(string $libelleDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleDocument', [$libelleDocument]);

        return parent::setLibelleDocument($libelleDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureCreation', []);

        return parent::getHeureCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureCreation($heureCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureCreation', [$heureCreation]);

        return parent::setHeureCreation($heureCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureModification', []);

        return parent::getHeureModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureModification($heureModification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureModification', [$heureModification]);

        return parent::setHeureModification($heureModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoriqueOperationDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoriqueOperationDoc', []);

        return parent::getHistoriqueOperationDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function addHistoriqueOperationDoc(\App\Entity\admin\historisation\documentOperation\HistoriqueOperationDocument $historiqueOperationDoc): \App\Entity\admin\historisation\documentOperation\TypeDocument
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistoriqueOperationDoc', [$historiqueOperationDoc]);

        return parent::addHistoriqueOperationDoc($historiqueOperationDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHistoriqueOperationDoc(\App\Entity\admin\historisation\documentOperation\HistoriqueOperationDocument $historiqueOperationDoc): \App\Entity\admin\historisation\documentOperation\TypeDocument
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHistoriqueOperationDoc', [$historiqueOperationDoc]);

        return parent::removeHistoriqueOperationDoc($historiqueOperationDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoriqueOperationDoc($historiqueOperationDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoriqueOperationDoc', [$historiqueOperationDoc]);

        return parent::setHistoriqueOperationDoc($historiqueOperationDoc);
    }

}
