<?php

namespace App\Proxies\__CG__\App\Entity\admin;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personnel extends \App\Entity\admin\Personnel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Matricule', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Code_AgenceService_Sage', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Numero_Fournisseur_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Code_AgenceService_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Numero_Telephone', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Numero_Compte_Bancaire', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Date_creation', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Libelle_AgenceService_Sage', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Code_Service_Agence_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Libelle_Service_Agence_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Prenoms', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Qualification', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'users', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'agenceServiceIriumId'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Matricule', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Code_AgenceService_Sage', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Numero_Fournisseur_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Code_AgenceService_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Numero_Telephone', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Numero_Compte_Bancaire', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Date_creation', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Libelle_AgenceService_Sage', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Code_Service_Agence_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Libelle_Service_Agence_IRIUM', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Prenoms', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'Qualification', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'users', '' . "\0" . 'App\\Entity\\admin\\Personnel' . "\0" . 'agenceServiceIriumId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personnel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(int $Matricule): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$Matricule]);

        return parent::setMatricule($Matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(?string $Nom): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$Nom]);

        return parent::setNom($Nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeAgenceServiceSage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAgenceServiceSage', []);

        return parent::getCodeAgenceServiceSage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAgenceServiceSage(?string $Code_AgenceService_Sage): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAgenceServiceSage', [$Code_AgenceService_Sage]);

        return parent::setCodeAgenceServiceSage($Code_AgenceService_Sage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFournisseurIRIUM(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFournisseurIRIUM', []);

        return parent::getNumeroFournisseurIRIUM();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFournisseurIRIUM(?int $Numero_Fournisseur_IRIUM): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFournisseurIRIUM', [$Numero_Fournisseur_IRIUM]);

        return parent::setNumeroFournisseurIRIUM($Numero_Fournisseur_IRIUM);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeAgenceServiceIRIUM(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAgenceServiceIRIUM', []);

        return parent::getCodeAgenceServiceIRIUM();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAgenceServiceIRIUM(?int $Code_AgenceService_IRIUM): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAgenceServiceIRIUM', [$Code_AgenceService_IRIUM]);

        return parent::setCodeAgenceServiceIRIUM($Code_AgenceService_IRIUM);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTelephone', []);

        return parent::getNumeroTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTelephone(?string $Numero_Telephone): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTelephone', [$Numero_Telephone]);

        return parent::setNumeroTelephone($Numero_Telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCompteBancaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCompteBancaire', []);

        return parent::getNumeroCompteBancaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCompteBancaire(string $Numero_Compte_Bancaire): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCompteBancaire', [$Numero_Compte_Bancaire]);

        return parent::setNumeroCompteBancaire($Numero_Compte_Bancaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', []);

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation(?\DateTime $Date_creation): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', [$Date_creation]);

        return parent::setDatecreation($Date_creation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleAgenceServiceSage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleAgenceServiceSage', []);

        return parent::getLibelleAgenceServiceSage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleAgenceServiceSage(?string $Libelle_AgenceService_Sage): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleAgenceServiceSage', [$Libelle_AgenceService_Sage]);

        return parent::setLibelleAgenceServiceSage($Libelle_AgenceService_Sage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeServiceAgenceIRIUM(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeServiceAgenceIRIUM', []);

        return parent::getCodeServiceAgenceIRIUM();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeServiceAgenceIRIUM(?string $Code_Service_Agence_IRIUM): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeServiceAgenceIRIUM', [$Code_Service_Agence_IRIUM]);

        return parent::setCodeServiceAgenceIRIUM($Code_Service_Agence_IRIUM);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenoms(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenoms', []);

        return parent::getPrenoms();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenoms(string $Prenoms): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenoms', [$Prenoms]);

        return parent::setPrenoms($Prenoms);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualification(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualification', []);

        return parent::getQualification();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualification(string $Qualification): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualification', [$Qualification]);

        return parent::setQualification($Qualification);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleServiceAgenceIRIUM(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleServiceAgenceIRIUM', []);

        return parent::getLibelleServiceAgenceIRIUM();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleServiceAgenceIRIUM(?string $Libelle_Service_Agence_IRIUM): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleServiceAgenceIRIUM', [$Libelle_Service_Agence_IRIUM]);

        return parent::setLibelleServiceAgenceIRIUM($Libelle_Service_Agence_IRIUM);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\App\Entity\admin\utilisateur\User $user): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', [$user]);

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\App\Entity\admin\utilisateur\User $user): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', [$user]);

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsers($users): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsers', [$users]);

        return parent::setUsers($users);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenceServiceIriumId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenceServiceIriumId', []);

        return parent::getAgenceServiceIriumId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgenceServiceIriumId($agenceServiceIriumId): \App\Entity\admin\Personnel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgenceServiceIriumId', [$agenceServiceIriumId]);

        return parent::setAgenceServiceIriumId($agenceServiceIriumId);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
