<?php

namespace App\Proxies\__CG__\App\Entity\admin\dom;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Indemnite extends \App\Entity\admin\dom\Indemnite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'site', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'rmq', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'sousTypeDoc', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'dateModification'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'site', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'rmq', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'sousTypeDoc', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\dom\\Indemnite' . "\0" . 'dateModification'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Indemnite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant(int $montant): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?\App\Entity\admin\dom\Catg
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\admin\dom\Catg $categorie): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite(): ?\App\Entity\admin\dom\Site
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', []);

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite(?\App\Entity\admin\dom\Site $site): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', [$site]);

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getRmq(): ?\App\Entity\admin\dom\Rmq
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRmq', []);

        return parent::getRmq();
    }

    /**
     * {@inheritDoc}
     */
    public function setRmq(?\App\Entity\admin\dom\Rmq $rmq): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRmq', [$rmq]);

        return parent::setRmq($rmq);
    }

    /**
     * {@inheritDoc}
     */
    public function getSousTypeDoc(): ?\App\Entity\admin\dom\SousTypeDocument
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousTypeDoc', []);

        return parent::getSousTypeDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousTypeDoc(?\App\Entity\admin\dom\SousTypeDocument $sousTypeDoc): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousTypeDoc', [$sousTypeDoc]);

        return parent::setSousTypeDoc($sousTypeDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTimeInterface $dateModification): \App\Entity\admin\dom\Indemnite
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        parent::onPreUpdate();
    }

}
