<?php

namespace App\Proxies\__CG__\App\Entity\admin;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AgenceServiceIrium extends \App\Entity\admin\AgenceServiceIrium implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'idIrium', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'agence_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'nom_agence_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'service_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'nom_service_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'agence_ips', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'service_ips', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'libelle_service_ips', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'societe_ios', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'service_sage_paie', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'userAgenceService', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'personnelId'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'idIrium', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'agence_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'nom_agence_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'service_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'nom_service_i100', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'agence_ips', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'service_ips', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'libelle_service_ips', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'societe_ios', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'service_sage_paie', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'userAgenceService', '' . "\0" . 'App\\Entity\\admin\\AgenceServiceIrium' . "\0" . 'personnelId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AgenceServiceIrium $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdirium(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdirium', []);

        return parent::getIdirium();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdirium(?string $id_irium): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdirium', [$id_irium]);

        return parent::setIdirium($id_irium);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencei100(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencei100', []);

        return parent::getAgencei100();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencei100(?string $agence_i100): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencei100', [$agence_i100]);

        return parent::setAgencei100($agence_i100);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomagencei100(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomagencei100', []);

        return parent::getNomagencei100();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomagencei100(?string $nom_agence_i100): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomagencei100', [$nom_agence_i100]);

        return parent::setNomagencei100($nom_agence_i100);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicei100(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicei100', []);

        return parent::getServicei100();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicei100(?string $service_i100): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicei100', [$service_i100]);

        return parent::setServicei100($service_i100);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomservicei100(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomservicei100', []);

        return parent::getNomservicei100();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomservicei100(?string $nom_service_i100): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomservicei100', [$nom_service_i100]);

        return parent::setNomservicei100($nom_service_i100);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgenceips(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgenceips', []);

        return parent::getAgenceips();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgenceips(?string $agence_ips): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgenceips', [$agence_ips]);

        return parent::setAgenceips($agence_ips);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceips(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceips', []);

        return parent::getServiceips();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceips(?string $service_ips): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceips', [$service_ips]);

        return parent::setServiceips($service_ips);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleserviceips(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleserviceips', []);

        return parent::getLibelleserviceips();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleserviceips(?string $libelle_service_ips): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleserviceips', [$libelle_service_ips]);

        return parent::setLibelleserviceips($libelle_service_ips);
    }

    /**
     * {@inheritDoc}
     */
    public function getSocieteios(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSocieteios', []);

        return parent::getSocieteios();
    }

    /**
     * {@inheritDoc}
     */
    public function setSocieteios(?string $societe_ios): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSocieteios', [$societe_ios]);

        return parent::setSocieteios($societe_ios);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicesagepaie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicesagepaie', []);

        return parent::getServicesagepaie();
    }

    /**
     * {@inheritDoc}
     */
    public function setService_sage_paie(?string $service_sage_paie): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService_sage_paie', [$service_sage_paie]);

        return parent::setService_sage_paie($service_sage_paie);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAgenceService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAgenceService', []);

        return parent::getUserAgenceService();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserAgenceService(\App\Entity\admin\utilisateur\User $userAgenceService): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserAgenceService', [$userAgenceService]);

        return parent::addUserAgenceService($userAgenceService);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserAgenceService(\App\Entity\admin\utilisateur\User $userAgenceService): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserAgenceService', [$userAgenceService]);

        return parent::removeUserAgenceService($userAgenceService);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAgenceService($userAgenceService)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAgenceService', [$userAgenceService]);

        return parent::setUserAgenceService($userAgenceService);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonnelId(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonnelId', []);

        return parent::getPersonnelId();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersonnelId(\App\Entity\admin\Personnel $personnelId): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersonnelId', [$personnelId]);

        return parent::addPersonnelId($personnelId);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersonnelId(\App\Entity\admin\Personnel $personnelId): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersonnelId', [$personnelId]);

        return parent::removePersonnelId($personnelId);
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonnelId($personnelId): \App\Entity\admin\AgenceServiceIrium
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonnelId', [$personnelId]);

        return parent::setPersonnelId($personnelId);
    }

}
