<?php

namespace App\Proxies\__CG__\App\Entity\admin\tik;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TkiSousCategorie extends \App\Entity\admin\tik\TkiSousCategorie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'description', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'autresCategories', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'supportInfo', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'dateModification'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'description', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'categories', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'autresCategories', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'supportInfo', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\tik\\TkiSousCategorie' . "\0" . 'dateModification'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TkiSousCategorie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategorie(\App\Entity\admin\tik\TkiCategorie $categorie): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategorie', [$categorie]);

        return parent::addCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories(\Doctrine\Common\Collections\Collection $categorie): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', [$categorie]);

        return parent::setCategories($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategorie(\App\Entity\admin\tik\TkiCategorie $categorie): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategorie', [$categorie]);

        return parent::removeCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutresCategories(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutresCategories', []);

        return parent::getAutresCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addAutresCategorie(\App\Entity\admin\tik\TkiAutresCategorie $autresCategorie): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAutresCategorie', [$autresCategorie]);

        return parent::addAutresCategorie($autresCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function setAutresCategories(\Doctrine\Common\Collections\Collection $autresCategorie): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutresCategories', [$autresCategorie]);

        return parent::setAutresCategories($autresCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAutresCategorie(\App\Entity\admin\tik\TkiAutresCategorie $autresCategorie): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAutresCategorie', [$autresCategorie]);

        return parent::removeAutresCategorie($autresCategorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupportInfo(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupportInfo', []);

        return parent::getSupportInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function addSupportInfo(?\App\Entity\tik\DemandeSupportInformatique $supportInfo): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSupportInfo', [$supportInfo]);

        return parent::addSupportInfo($supportInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSupportInfo(?\App\Entity\tik\DemandeSupportInformatique $supportInfo): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSupportInfo', [$supportInfo]);

        return parent::removeSupportInfo($supportInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTimeInterface $dateModification): \App\Entity\admin\tik\TkiSousCategorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        parent::onPreUpdate();
    }

}
