<?php

namespace App\Proxies\__CG__\App\Entity\cde;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CdefnrSoumisAValidation extends \App\Entity\cde\CdefnrSoumisAValidation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'numCdeFournisseur', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'codeFournisseur', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'numVersion', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'dateHeureSoumission', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'nomFichier', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'numeroDa', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'pieceJoint01', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'pieceJoint02'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'numCdeFournisseur', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'codeFournisseur', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'numVersion', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'dateHeureSoumission', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'nomFichier', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'numeroDa', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'pieceJoint01', '' . "\0" . 'App\\Entity\\cde\\CdefnrSoumisAValidation' . "\0" . 'pieceJoint02'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CdefnrSoumisAValidation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumCdeFournisseur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumCdeFournisseur', []);

        return parent::getNumCdeFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumCdeFournisseur($numCdeFournisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumCdeFournisseur', [$numCdeFournisseur]);

        return parent::setNumCdeFournisseur($numCdeFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeFournisseur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeFournisseur', []);

        return parent::getCodeFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeFournisseur($codeFournisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeFournisseur', [$codeFournisseur]);

        return parent::setCodeFournisseur($codeFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumVersion', []);

        return parent::getNumVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumVersion($numVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumVersion', [$numVersion]);

        return parent::setNumVersion($numVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateHeureSoumission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateHeureSoumission', []);

        return parent::getDateHeureSoumission();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateHeureSoumission($dateHeureSoumission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateHeureSoumission', [$dateHeureSoumission]);

        return parent::setDateHeureSoumission($dateHeureSoumission);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomFichier', []);

        return parent::getNomFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomFichier($nomFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomFichier', [$nomFichier]);

        return parent::setNomFichier($nomFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDa', []);

        return parent::getNumeroDa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDa($numeroDa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDa', [$numeroDa]);

        return parent::setNumeroDa($numeroDa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPieceJoint01()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPieceJoint01', []);

        return parent::getPieceJoint01();
    }

    /**
     * {@inheritDoc}
     */
    public function setPieceJoint01($pieceJoint01)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPieceJoint01', [$pieceJoint01]);

        return parent::setPieceJoint01($pieceJoint01);
    }

    /**
     * {@inheritDoc}
     */
    public function getPieceJoint02()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPieceJoint02', []);

        return parent::getPieceJoint02();
    }

    /**
     * {@inheritDoc}
     */
    public function setPieceJoint02($pieceJoint02)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPieceJoint02', [$pieceJoint02]);

        return parent::setPieceJoint02($pieceJoint02);
    }

}
