<?php

namespace App\Proxies\__CG__\App\Entity\ddp;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DemandePaiementLigne extends \App\Entity\ddp\DemandePaiementLigne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroDdp', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroLigne', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroCommande', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroFacture', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'montantFacture', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroVersion', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'dateModification'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroDdp', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroLigne', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroCommande', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroFacture', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'montantFacture', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'numeroVersion', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\ddp\\DemandePaiementLigne' . "\0" . 'dateModification'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DemandePaiementLigne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDdp', []);

        return parent::getNumeroDdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDdp($numeroDdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDdp', [$numeroDdp]);

        return parent::setNumeroDdp($numeroDdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroLigne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroLigne', []);

        return parent::getNumeroLigne();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroLigne($numeroLigne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroLigne', [$numeroLigne]);

        return parent::setNumeroLigne($numeroLigne);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCommande', []);

        return parent::getNumeroCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCommande($numeroCommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCommande', [$numeroCommande]);

        return parent::setNumeroCommande($numeroCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroFacture', []);

        return parent::getNumeroFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroFacture($numeroFacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroFacture', [$numeroFacture]);

        return parent::setNumeroFacture($numeroFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantFacture', []);

        return parent::getMontantFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantFacture($montantFacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantFacture', [$montantFacture]);

        return parent::setMontantFacture($montantFacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroVersion', []);

        return parent::getNumeroVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroVersion($numeroVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroVersion', [$numeroVersion]);

        return parent::setNumeroVersion($numeroVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\ddp\DemandePaiementLigne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTimeInterface $dateModification): \App\Entity\ddp\DemandePaiementLigne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        parent::onPreUpdate();
    }

}
