<?php

namespace App\Proxies\__CG__\App\Entity\admin\tik;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProjetInformatique extends \App\Entity\admin\tik\ProjetInformatique implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'numeroDemandeur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'mailDemandeur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'codeSociete', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'idTkiCategorie', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'idTkiSousCategorie', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'agenceServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'agenceServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'nomIntervenant', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'mailIntervenant', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'objetDemande', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'detailDemande', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'pieceJointe1', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'pieceJointe2', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'pieceJointe3', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'dateDebPlanning', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'dateFinPlanning', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'avancementProjet'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'numeroDemandeur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'mailDemandeur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'codeSociete', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'idTkiCategorie', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'idTkiSousCategorie', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'agenceServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'agenceServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'nomIntervenant', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'mailIntervenant', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'objetDemande', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'detailDemande', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'pieceJointe1', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'pieceJointe2', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'pieceJointe3', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'dateDebPlanning', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'dateFinPlanning', '' . "\0" . 'App\\Entity\\admin\\tik\\ProjetInformatique' . "\0" . 'avancementProjet'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProjetInformatique $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
}
