<?php

namespace App\Proxies\__CG__\App\Entity\admin;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StatutDemande extends \App\Entity\admin\StatutDemande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'codeApp', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'codeStatut', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'description', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'badms', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'demandeInterventions', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'casiers', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'doms', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'mutation', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'supportInfo', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'statutTik', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'dateModification'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'codeApp', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'codeStatut', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'description', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'badms', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'demandeInterventions', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'casiers', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'doms', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'mutation', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'supportInfo', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'statutTik', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\StatutDemande' . "\0" . 'dateModification'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StatutDemande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeApp(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeApp', []);

        return parent::getCodeApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeApp(string $codeApp): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeApp', [$codeApp]);

        return parent::setCodeApp($codeApp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeStatut(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeStatut', []);

        return parent::getCodeStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeStatut(string $codeStatut): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeStatut', [$codeStatut]);

        return parent::setCodeStatut($codeStatut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getBadms(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBadms', []);

        return parent::getBadms();
    }

    /**
     * {@inheritDoc}
     */
    public function addBadm(\App\Entity\badm\Badm $badm): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBadm', [$badm]);

        return parent::addBadm($badm);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBadm(\App\Entity\badm\Badm $badm): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBadm', [$badm]);

        return parent::removeBadm($badm);
    }

    /**
     * {@inheritDoc}
     */
    public function setBadms($badms): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBadms', [$badms]);

        return parent::setBadms($badms);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDemandeInterventions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemandeInterventions', []);

        return parent::getDemandeInterventions();
    }

    /**
     * {@inheritDoc}
     */
    public function addDemandeIntervention(\App\Entity\dit\DemandeIntervention $demandeIntervention): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDemandeIntervention', [$demandeIntervention]);

        return parent::addDemandeIntervention($demandeIntervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDemandeIntervention(\App\Entity\dit\DemandeIntervention $demandeIntervention): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDemandeIntervention', [$demandeIntervention]);

        return parent::removeDemandeIntervention($demandeIntervention);
    }

    /**
     * {@inheritDoc}
     */
    public function setDemandeInterventions($demandeInterventions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemandeInterventions', [$demandeInterventions]);

        return parent::setDemandeInterventions($demandeInterventions);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasiers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasiers', []);

        return parent::getCasiers();
    }

    /**
     * {@inheritDoc}
     */
    public function addCasier(\App\Entity\cas\Casier $casier): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCasier', [$casier]);

        return parent::addCasier($casier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCasier(\App\Entity\cas\Casier $casier): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCasier', [$casier]);

        return parent::removeCasier($casier);
    }

    /**
     * {@inheritDoc}
     */
    public function setCasiers($casier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasiers', [$casier]);

        return parent::setCasiers($casier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoms', []);

        return parent::getDoms();
    }

    /**
     * {@inheritDoc}
     */
    public function addDom(\App\Entity\dom\Dom $doms): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDom', [$doms]);

        return parent::addDom($doms);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDom(\App\Entity\dom\Dom $doms): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDom', [$doms]);

        return parent::removeDom($doms);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoms($doms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoms', [$doms]);

        return parent::setDoms($doms);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupportInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupportInfo', []);

        return parent::getSupportInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function addSupportInfo(\App\Entity\tik\DemandeSupportInformatique $supportInfo): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSupportInfo', [$supportInfo]);

        return parent::addSupportInfo($supportInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSupportInfo(\App\Entity\tik\DemandeSupportInformatique $supportInfo): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSupportInfo', [$supportInfo]);

        return parent::removeSupportInfo($supportInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutTik()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutTik', []);

        return parent::getStatutTik();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatutTik(\App\Entity\admin\tik\TkiStatutTicketInformatique $statutTik): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatutTik', [$statutTik]);

        return parent::addStatutTik($statutTik);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatutTik(\App\Entity\admin\tik\TkiStatutTicketInformatique $statutTik): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatutTik', [$statutTik]);

        return parent::removeStatutTik($statutTik);
    }

    /**
     * {@inheritDoc}
     */
    public function getMutation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMutation', []);

        return parent::getMutation();
    }

    /**
     * {@inheritDoc}
     */
    public function addMutation(\App\Entity\mutation\Mutation $mutation): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMutation', [$mutation]);

        return parent::addMutation($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMutation(\App\Entity\mutation\Mutation $mutation): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMutation', [$mutation]);

        return parent::removeMutation($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function setMutation($mutation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMutation', [$mutation]);

        return parent::setMutation($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTimeInterface $dateModification): \App\Entity\admin\StatutDemande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        parent::onPreUpdate();
    }

}
