<?php

namespace App\Proxies\__CG__\App\Entity\admin;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Service extends \App\Entity\admin\Service implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'codeService', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'libelleService', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'agences', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'ditServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'ditServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'badmServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'badmServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'domServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'domServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'userServiceAutoriser', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'tkiServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'tkiServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'mutationServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'mutationServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'dateModification'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'id', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'codeService', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'libelleService', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'agences', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'ditServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'ditServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'badmServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'badmServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'domServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'domServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'userServiceAutoriser', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'tkiServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'tkiServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'mutationServiceEmetteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'mutationServiceDebiteur', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\admin\\Service' . "\0" . 'dateModification'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Service $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeService', []);

        return parent::getCodeService();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeService($codeService): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeService', [$codeService]);

        return parent::setCodeService($codeService);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelleService()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelleService', []);

        return parent::getLibelleService();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelleService(string $libelleService): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelleService', [$libelleService]);

        return parent::setLibelleService($libelleService);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgences(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgences', []);

        return parent::getAgences();
    }

    /**
     * {@inheritDoc}
     */
    public function addAgence(\App\Entity\admin\Agence $agence): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAgence', [$agence]);

        return parent::addAgence($agence);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAgence(\App\Entity\admin\Agence $agence): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAgence', [$agence]);

        return parent::removeAgence($agence);
    }

    /**
     * {@inheritDoc}
     */
    public function getDitServiceEmetteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDitServiceEmetteurs', []);

        return parent::getDitServiceEmetteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addDitServiceEmetteur(\App\Entity\dit\DemandeIntervention $demandeIntervention): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDitServiceEmetteur', [$demandeIntervention]);

        return parent::addDitServiceEmetteur($demandeIntervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDitServiceEmetteur(\App\Entity\dit\DemandeIntervention $ditAgenceEmetteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDitServiceEmetteur', [$ditAgenceEmetteur]);

        return parent::removeDitServiceEmetteur($ditAgenceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setDitServiceEmetteurs($ditAgenceEmetteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDitServiceEmetteurs', [$ditAgenceEmetteur]);

        return parent::setDitServiceEmetteurs($ditAgenceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDitServiceDebiteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDitServiceDebiteurs', []);

        return parent::getDitServiceDebiteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addDitServiceDebiteurs(\App\Entity\dit\DemandeIntervention $demandeIntervention): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDitServiceDebiteurs', [$demandeIntervention]);

        return parent::addDitServiceDebiteurs($demandeIntervention);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDitServiceDebiteur(\App\Entity\dit\DemandeIntervention $ditAgenceDebiteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDitServiceDebiteur', [$ditAgenceDebiteur]);

        return parent::removeDitServiceDebiteur($ditAgenceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setDitServiceDebiteurs($ditAgenceDebiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDitServiceDebiteurs', [$ditAgenceDebiteur]);

        return parent::setDitServiceDebiteurs($ditAgenceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getbadmServiceEmetteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getbadmServiceEmetteurs', []);

        return parent::getbadmServiceEmetteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addbadmServiceEmetteur(\App\Entity\badm\Badm $badm): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addbadmServiceEmetteur', [$badm]);

        return parent::addbadmServiceEmetteur($badm);
    }

    /**
     * {@inheritDoc}
     */
    public function removebadmServiceEmetteur(\App\Entity\badm\Badm $badmAgenceEmetteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removebadmServiceEmetteur', [$badmAgenceEmetteur]);

        return parent::removebadmServiceEmetteur($badmAgenceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setbadmServiceEmetteurs($badmAgenceEmetteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setbadmServiceEmetteurs', [$badmAgenceEmetteur]);

        return parent::setbadmServiceEmetteurs($badmAgenceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getBadmServiceDebiteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBadmServiceDebiteurs', []);

        return parent::getBadmServiceDebiteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addBadmServiceDebiteurs(\App\Entity\badm\Badm $badm): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBadmServiceDebiteurs', [$badm]);

        return parent::addBadmServiceDebiteurs($badm);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBadmServiceDebiteur(\App\Entity\badm\Badm $badmAgenceDebiteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBadmServiceDebiteur', [$badmAgenceDebiteur]);

        return parent::removeBadmServiceDebiteur($badmAgenceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setBadmServiceDebiteurs($badmAgenceDebiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBadmServiceDebiteurs', [$badmAgenceDebiteur]);

        return parent::setBadmServiceDebiteurs($badmAgenceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserServiceAutoriser(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserServiceAutoriser', []);

        return parent::getUserServiceAutoriser();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserServiceAutoriser(\App\Entity\admin\utilisateur\User $userServiceAutoriser): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserServiceAutoriser', [$userServiceAutoriser]);

        return parent::addUserServiceAutoriser($userServiceAutoriser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserServiceAutoriser(\App\Entity\admin\utilisateur\User $userServiceAutoriser): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserServiceAutoriser', [$userServiceAutoriser]);

        return parent::removeUserServiceAutoriser($userServiceAutoriser);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomServiceEmetteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomServiceEmetteurs', []);

        return parent::getDomServiceEmetteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addDomServiceEmetteur(\App\Entity\dom\Dom $domServiceEmetteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDomServiceEmetteur', [$domServiceEmetteur]);

        return parent::addDomServiceEmetteur($domServiceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDomServiceEmetteur(\App\Entity\dom\Dom $domServiceEmetteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDomServiceEmetteur', [$domServiceEmetteur]);

        return parent::removeDomServiceEmetteur($domServiceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setDomServiceEmetteurs($domServiceEmetteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomServiceEmetteurs', [$domServiceEmetteur]);

        return parent::setDomServiceEmetteurs($domServiceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomServiceDebiteurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomServiceDebiteurs', []);

        return parent::getDomServiceDebiteurs();
    }

    /**
     * {@inheritDoc}
     */
    public function addDomServiceDebiteurs(\App\Entity\dom\Dom $domServiceDebiteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDomServiceDebiteurs', [$domServiceDebiteur]);

        return parent::addDomServiceDebiteurs($domServiceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDomServiceDebiteur(\App\Entity\dom\Dom $domServiceDebiteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDomServiceDebiteur', [$domServiceDebiteur]);

        return parent::removeDomServiceDebiteur($domServiceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setDomServiceDebiteurs($domServiceDebiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomServiceDebiteurs', [$domServiceDebiteur]);

        return parent::setDomServiceDebiteurs($domServiceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTkiServiceEmetteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTkiServiceEmetteur', []);

        return parent::getTkiServiceEmetteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addTkiServiceEmetteur(\App\Entity\tik\DemandeSupportInformatique $tkiServiceEmetteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTkiServiceEmetteur', [$tkiServiceEmetteur]);

        return parent::addTkiServiceEmetteur($tkiServiceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTkiServiceEmetteur(\App\Entity\tik\DemandeSupportInformatique $tkiServiceEmetteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTkiServiceEmetteur', [$tkiServiceEmetteur]);

        return parent::removeTkiServiceEmetteur($tkiServiceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTkiServiceDebiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTkiServiceDebiteur', []);

        return parent::getTkiServiceDebiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addTkiServiceDebiteur(\App\Entity\tik\DemandeSupportInformatique $tkiServiceDebiteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTkiServiceDebiteur', [$tkiServiceDebiteur]);

        return parent::addTkiServiceDebiteur($tkiServiceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTkiServiceDebiteur(\App\Entity\tik\DemandeSupportInformatique $tkiServiceDebiteur): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTkiServiceDebiteur', [$tkiServiceDebiteur]);

        return parent::removeTkiServiceDebiteur($tkiServiceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getMutationServiceEmetteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMutationServiceEmetteur', []);

        return parent::getMutationServiceEmetteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addMutationServiceEmetteur(\App\Entity\mutation\Mutation $mutation): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMutationServiceEmetteur', [$mutation]);

        return parent::addMutationServiceEmetteur($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMutationServiceEmetteur(\App\Entity\mutation\Mutation $mutation): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMutationServiceEmetteur', [$mutation]);

        return parent::removeMutationServiceEmetteur($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function setMutationServiceEmetteur($mutationServiceEmetteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMutationServiceEmetteur', [$mutationServiceEmetteur]);

        return parent::setMutationServiceEmetteur($mutationServiceEmetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getMutationServiceDebiteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMutationServiceDebiteur', []);

        return parent::getMutationServiceDebiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function addMutationServiceDebiteur(\App\Entity\mutation\Mutation $mutation): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMutationServiceDebiteur', [$mutation]);

        return parent::addMutationServiceDebiteur($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMutationServiceDebiteur(\App\Entity\mutation\Mutation $mutation): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMutationServiceDebiteur', [$mutation]);

        return parent::removeMutationServiceDebiteur($mutation);
    }

    /**
     * {@inheritDoc}
     */
    public function setMutationServiceDebiteur($mutationServiceDebiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMutationServiceDebiteur', [$mutationServiceDebiteur]);

        return parent::setMutationServiceDebiteur($mutationServiceDebiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTimeInterface $dateModification): \App\Entity\admin\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', []);

        parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate(): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', []);

        parent::onPreUpdate();
    }

}
