<?php

namespace App\Proxies\__CG__\App\Entity\dit;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BcSoumis extends \App\Entity\dit\BcSoumis implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'id', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numDit', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numDevis', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numBc', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numVersion', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'dateBc', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'dateDevis', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'montantDevis', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'dateHeureSoumission', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'nomFichier', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'statut'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'id', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numDit', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numDevis', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numBc', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'numVersion', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'dateBc', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'dateDevis', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'montantDevis', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'dateHeureSoumission', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'nomFichier', '' . "\0" . 'App\\Entity\\dit\\BcSoumis' . "\0" . 'statut'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BcSoumis $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumDit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumDit', []);

        return parent::getNumDit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumDit(string $numDit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumDit', [$numDit]);

        return parent::setNumDit($numDit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumDevis', []);

        return parent::getNumDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumDevis(string $numDevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumDevis', [$numDevis]);

        return parent::setNumDevis($numDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumBc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumBc', []);

        return parent::getNumBc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumBc(string $numBc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumBc', [$numBc]);

        return parent::setNumBc($numBc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumVersion', []);

        return parent::getNumVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumVersion($numVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumVersion', [$numVersion]);

        return parent::setNumVersion($numVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateBc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateBc', []);

        return parent::getDateBc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateBc($dateBc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateBc', [$dateBc]);

        return parent::setDateBc($dateBc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDevis', []);

        return parent::getDateDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDevis($dateDevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDevis', [$dateDevis]);

        return parent::setDateDevis($dateDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantDevis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantDevis', []);

        return parent::getMontantDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantDevis($montantDevis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantDevis', [$montantDevis]);

        return parent::setMontantDevis($montantDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateHeureSoumission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateHeureSoumission', []);

        return parent::getDateHeureSoumission();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateHeureSoumission($dateHeureSoumission)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateHeureSoumission', [$dateHeureSoumission]);

        return parent::setDateHeureSoumission($dateHeureSoumission);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomFichier', []);

        return parent::getNomFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomFichier($nomFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomFichier', [$nomFichier]);

        return parent::setNomFichier($nomFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

}
