# Configuration des formulaires
framework:
    form:
        enabled: true
        csrf_protection:
            enabled: '%security.csrf.enabled%'
        default_theme: '%form.default_theme%'
        csrf_field_name: '_token'
        csrf_token_id: 'form'
    
    # Configuration de la validation
    validation:
        enabled: true
        enable_annotations: true
        mapping:
            paths: []
    
    # Configuration des assets
    assets:
        enabled: true
        packages:
            public:
                base_path: '%app.public_dir%'
                version: '%app.version%'
                version_format: '%%s?version=%%s'
    
    # Configuration de la sécurité
    security:
        enabled: true
        csrf_protection:
            enabled: '%security.csrf.enabled%'
        session_fixation_strategy: '%security.session_fixation_strategy%'
    
    # Configuration des sessions
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    # Configuration des traductions
    translator:
        enabled: true
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        logging: '%app.debug%'
    
    # Configuration du routage
    router:
        enabled: true
        default_uri: null
        utf8: true
        strict_requirements:
            enabled: '%app.debug%'
            log_missing: '%app.debug%'
    
    # Configuration des profilers
    profiler:
        enabled: '%app.debug%'
        collect: true
        only_exceptions: false
        only_master_requests: false
        dsn: 'file:%kernel.cache_dir%/profiler'
    
    # Configuration des web profilers
    web_profiler:
        enabled: '%app.debug%'
        toolbar: '%app.debug%'
        intercept_redirects: false
        exclude_ajax: false
        exclude_paths: []
        exclude_sections: []
