# Paramètres de l'application
parameters:
    # Configuration de l'application
    app.name: 'Hffintranet'
    app.version: '1.0.0'
    app.locale: 'fr_FR'
    app.debug: true
    app.environment: 'dev'
    
    # Chemins de base
    app.base_path: '%env(BASE_PATH_COURT)%'
    app.views_dir: 'Views/templates'
    app.public_dir: 'public'
    
    # Configuration de la base de données
    database_host: '%env(DB_HOST)%'
    database_port: '%env(DB_PORT)%'
    database_name: '%env(DB_NAME)%'
    database_user: '%env(DB_USER)%'
    database_password: '%env(DB_PASSWORD)%'
    
    # Configuration des sessions
    session.name: 'HFFSESSION'
    session.lifetime: 3600
    
    # Configuration de la sécurité
    security.csrf.enabled: true
    security.session_fixation_strategy: 'migrate'
    
    # Configuration Twig
    twig.debug: true
    twig.strict_variables: false
    twig.form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form_div_layout.html.twig'
    
    # Configuration des formulaires
    form.default_theme: 'bootstrap_5_layout.html.twig'
    
    # Configuration de la pagination
    pagination.items_per_page: 20
    pagination.max_pages: 10

    # Configuration du Mailer
    mailer.host: '%env(MAILER_HOST)%'
    mailer.port: '%env(MAILER_PORT)%'
    mailer.user: '%env(MAILER_USER)%'
    mailer.password: '%env(MAILER_PASSWORD)%'
    mailer.from_email: 'noreply.email@hff.mg'
    mailer.from_name: 'noreply'
    mailer.bcc_recipients:
        - 'ranofimenjajam@gmail.com'
        - 'hasina.andrianadison@hff.mg'

    # Configuration Docuware
    docuware.ftp_path: '%env(BASE_PATH_DOCUWARE)%'

    # Configuration Upload
    upload_directory: '%env(BASE_PATH_FICHIER)%'

    # Paramètres LDAP
    ldap.host: '%env(LDAP_HOST)%'
    ldap.port: '%env(LDAP_PORT)%'
    ldap.domain: '%env(LDAP_DOMAIN)%'
    ldap.dn: '%env(LDAP_DN)%'

    # Chemin du fichier CSV d'authentification
    auth.csv_file_path: '%kernel.project_dir%/src/Controller/authentification.csv'

    # Paramètres de connexion ODBC
    odbc.main.dsn: '%env(DB_DNS_SQLSERV)%'
    odbc.main.user: '%env(DB_USERNAME_SQLSERV)%'
    odbc.main.password: '%env(DB_PASSWORD_SQLSERV)%'

    odbc.dote4.dsn: '%env(DB_DNS_SQLSERV_4)%'
    odbc.dote4.user: '%env(DB_USERNAME_SQLSERV_4)%'
    odbc.dote4.password: '%env(DB_PASSWORD_SQLSERV_4)%'

    odbc.dote4gc.dsn: '%env(DB_DNS_SQLSERV_4_GCOT)%'
    odbc.dote4gc.user: '%env(DB_USERNAME_SQLSERV_4)%'
    odbc.dote4gc.password: '%env(DB_PASSWORD_SQLSERV_4)%'

    odbc.informix.dsn: '%env(DB_DNS_INFORMIX)%'
    odbc.informix.user: '%env(DB_USERNAME_INFORMIX)%'
    odbc.informix.password: '%env(DB_PASSWORD_INFORMIX)%'

    # Chemin pour les logs d'erreur
    app.error_log_path: '%env(BASE_PATH_LOG)%'

    # Chemins de base supplémentaires
    app.base_path_long: '%env(BASE_PATH_LONG)%'
    app.base_path_court: '%env(BASE_PATH_COURT)%'
    app.base_path_fichier_court: '%env(BASE_PATH_FICHIER_COURT)%'
